HospitalERP.Web/Controllers/RoleController.cs
using HospitalERP.Entities;
using HospitalERP.ViewModels;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;

namespace HospitalERP.Web.Controllers
{
    public class RoleController : Controller
    {
        private readonly RoleManager<IdentityRole> roleManager;
        private readonly UserManager<User> userManager;

        public RoleController(RoleManager<IdentityRole> roleManager, UserManager<User> userManager)
        {
            this.roleManager = roleManager;
            this.userManager = userManager;
        }

        [HttpGet]
        public IActionResult Index()
        {
            var roles = roleManager.Roles;
            return View(roles);
        }

        [HttpGet]
        public IActionResult CreateRole()
        {
            return View();
        }

        [HttpPost]
        public async Task<IActionResult> CreateRole(CreateRoleViewModel model)
        {
            if (ModelState.IsValid)
            {
                IdentityRole role = new IdentityRole()
                {
                    Name = model.RoleName
                };

                IdentityResult result = await roleManager.CreateAsync(role);

                if (result.Succeeded)
                {
                    return RedirectToAction("Index", "Hospital");
                }

                foreach (var item in result.Errors)
                {
                    ModelState.AddModelError("", item.Description);
                }
            }

            return View(model);
        }

        [HttpGet]
        public async Task<IActionResult> EditRole(string id)
        {
            var role = await roleManager.FindByIdAsync(id);

            if (role == null)
            {
                return RedirectToAction("NotFound", "Shared");
            }

            var model = new EditRoleViewModel
            {
                Id = role.Id,
                RoleName = role.Name
            };

            foreach (var user in userManager.Users)
            {
                if (await userManager.IsInRoleAsync(user, role.Name))
                {
                    model.Users.Add(user);
                }
            }

            return View(model);
        }

        [HttpPost]
        public async Task<IActionResult> EditRole(EditRoleViewModel model)
        {
            var role = await roleManager.FindByIdAsync(model.Id);

            if (role == null)
            {
                return RedirectToAction("NotFound", "Shared");
            }
            else
            {
                role.Name = model.RoleName;
                var result = await roleManager.UpdateAsync(role);

                if (result.Succeeded)
                {
                    return RedirectToAction("Index");
                }

                foreach (var item in result.Errors)
                {
                    ModelState.AddModelError("", item.Description);
                }
            }

            return View(model);

        }
    }
}

HospitalERP.Web/Controllers/SharedController.cs
using Microsoft.AspNetCore.Mvc;

namespace HospitalERP.Web.Controllers
{
    public class SharedController : Controller
    {
        [HttpPost]
        public IActionResult StoreNavigationClasses(string navigationClasses)
        {
            HttpContext.Session.SetString("bar-situation", navigationClasses);
            return Ok();
        }

        [HttpGet]
        public IActionResult NotFound()
        {
            return View();
        }
    }
}

HospitalERP.Web/Views/Shared/NotFound.cshtml
<div class="text-center">
    <br />
    <h1 class="text-danger">Role Does Not Exist!</h1>
    <h6 class="text-danger">Get back to the all roles.</h6>
    <a  asp-controller="Role" asp-action="Index" class="btn btn-danger">Roles</a>
    <img src="~/images/access-denied.png" height="500px" width="500px" />

</div>

HospitalERP.Web/Views/Shared/_Layout.cshtml
@inject IHttpContextAccessor context;
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>Hospital-ERP</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />

    <link rel="stylesheet" href="~/css/SideBar.css" asp-append-version="true" />


    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/HospitalERP.Web.styles.css" asp-append-version="true" />
    <link href='https://unpkg.com/boxicons@2.1.4/css/boxicons.min.css' rel='stylesheet'>


    <script src="https://unpkg.com/boxicons@2.1.4/dist/boxicons.js"></script>
    <script type="module" src="https://unpkg.com/ionicons@7.1.0/dist/ionicons/ionicons.esm.js"></script>
    <script nomodule src="https://unpkg.com/ionicons@7.1.0/dist/ionicons/ionicons.js"></script>
    <script src="https://code.jquery.com/jquery-3.6.4.min.js"></script>
   
</head>
<body>
    <div class="layout-container">
        <div class="navigation">
            <div class="toggle">
                <ion-icon name="menu-outline" class="open"></ion-icon>
                <ion-icon name="close-outline" class="close"></ion-icon>
            </div>
            <div class="main-pic">
                <img src="~/Static-Images/hospital.png" class="logo-img" />
            </div>
            <ul class="main-list">
                <li class="list Active hospitals">
                    <b></b>
                    <b></b>
                    <a href="~/Hospital/Index">
                        <span class="icon"><ion-icon name="business-outline"></ion-icon></span>
                        <span class="title">Hospitals</span>
                    </a>
                </li>
                <li class="list rooms">
                    <b></b>
                    <b></b>
                    <a href="~/Room/Index">
                        <span class="icon"><ion-icon name="bed-outline"></ion-icon></span>
                        <span class="title">Rooms</span>
                    </a>
                </li>
                <li class="list">
                    <b></b>
                    <b></b>
                    <a href="~/Patient/Index">
                        <span class="icon"><ion-icon name="person"></ion-icon></span>
                        <span class="title">Patients</span>
                    </a>
                </li>
                <li class="list">
                    <b></b>
                    <b></b>
                    <a href="~/Doctor/Index">
                        <span class="icon"><ion-icon name="person"></ion-icon></span>
                        <span class="title">Doctors</span>
                    </a>
                </li>
                <li class="list">
                    <b></b>
                    <b></b>
                    <a href="~/Compounder/Index">
                        <span class="icon"><ion-icon name="person"></ion-icon></span>
                        <span class="title">Compounder</span>
                    </a>
                </li>
                <li class="list">
                    <b></b>
                    <b></b>
                    <a href="~/Nurse/Index">
                        <span class="icon"><ion-icon name="person"></ion-icon></span>
                        <span class="title">Nurse</span>
                    </a>
                </li>
                <li class="list">
                    <b></b>
                    <b></b>
                    <a href="~/Supplier/Index">
                        <span class="icon"><ion-icon name="person"></ion-icon></span>
                        <span class="title">Suppliers</span>
                    </a>
                </li>
                <li class="list">
                    <b></b>
                    <b></b>
                    <a href="~/LabStaff/Index">
                        <span class="icon"><ion-icon name="person"></ion-icon></span>
                        <span class="title">Lab Staff</span>
                    </a>
                </li>
                <li class="list">
                    <b></b>
                    <b></b>
                    <a href="~/Pharmacist/Index">
                        <span class="icon"><ion-icon name="person"></ion-icon></span>
                        <span class="title">Pharmacist</span>
                    </a>
                </li>
                <li class="list">
                    <b></b>
                    <b></b>
                    <a href="~/Management/Index">
                        <span class="icon"><ion-icon name="person"></ion-icon></span>
                        <span class="title">Management</span>
                    </a>
                </li>
                <li class="list">
                    <b></b>
                    <b></b>
                    <a href="~/Security/Index">
                        <span class="icon"><ion-icon name="person"></ion-icon></span>
                        <span class="title">Security</span>
                    </a>
                </li>
                <li class="list">
                    <b></b>
                    <b></b>
                    <a href="~/Cleaner/Index">
                        <span class="icon"><ion-icon name="person"></ion-icon></span>
                        <span class="title">
                            Cleaner

                        </span>
                    </a>
                </li>
                <li class="list">
                    <b></b>
                    <b></b>
                    <a href="~/Maintenance/Index">
                        <span class="icon"><ion-icon name="person"></ion-icon></span>
                        <span class="title">Maintenance</span>
                    </a>
                </li>                
                <li class="list">
                    <b></b>
                    <b></b>
                    <a href="#">
                        <span class="icon"><ion-icon name="settings-outline"></ion-icon></span>
                        <span class="title">Setting</span>
                    </a>
                </li>
                <li class="list">
                    <b></b>
                    <b></b>
                    <a href="#">
                        <span class="icon"><ion-icon name="log-out-outline"></ion-icon></span>
                        <span class="title">Sign Out</span>
                    </a>
                </li>
            </ul>
        </div>

           <div class="main-content">
                @RenderBody()
           </div>

    </div>

    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    <script src="~/js/SideBar.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)

    <script>
        $(document).ready(function () {

            // Toggle menu
            $('.toggle').click(function () {

                $('.toggle, .navigation, .logo-img, .main-list, .main-content').toggleClass('Active');

                var navigationClasses = $('.navigation').attr('class');

                $.ajax({
                    url: '/Shared/StoreNavigationClasses',
                    method: 'POST',
                    data: { navigationClasses: navigationClasses },
                    success: function (response) {

                    },
                    error: function (error) {
                        console.error('Error storing class names:', error);
                    }
                });


            });

            var data = "@context.HttpContext.Session.GetString("nav-bar")";

            if (data === "rooms") {
                $('.list').removeClass('Active');
                $('.rooms').addClass('Active');
            }
            else if (data === "hospital") {
                $('.list').removeClass('Active');
                $('.hospitals').addClass('Active');
            }

            var barWidth = "@context.HttpContext.Session.GetString("bar-situation")";

            if (barWidth === "navigation Active") {
                $('.toggle, .navigation, .logo-img, .main-list, .main-content').addClass('Active');
            }
            else {
                $('.toggle, .navigation, .logo-img, .main-list, .main-content').removeClass('Active');
            }
        });
       
    </script>
</body>

</html>